const KEY='financeTrackerV1';
const state=JSON.parse(localStorage.getItem(KEY)||'{"accounts":[],"people":[],"bills":[],"payments":[]}');
const $=id=>document.getElementById(id); const money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(n)||0); const num=v=>Math.max(0,Number(v)||0);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const today=()=>{const d=new Date();return d.toISOString().slice(0,10)}; $('payDate').value=today();
function dateObj(s){if(!s)return null;const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)}
function daysUntil(s){const d=dateObj(s);if(!d)return 9999;const n=new Date();n.setHours(12,0,0,0);return Math.ceil((d-n)/86400000)}
function fmtDate(s){const d=dateObj(s);return d?new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',year:'numeric'}).format(d):'No date'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function empty(text){return `<div class="empty">${esc(text)}</div>`}
function render(){renderSummary();renderAccounts();renderPeople();renderBills();renderDashboard();renderPayoff();renderPayments();refreshPaymentItems();save()}
function renderSummary(){const debt=state.accounts.reduce((s,a)=>s+a.balance,0);const owe=state.people.filter(p=>p.dir==='i_owe').reduce((s,p)=>s+p.balance,0);const owed=state.people.filter(p=>p.dir==='owes_me').reduce((s,p)=>s+p.balance,0);const bills=state.bills.filter(b=>!b.paid).reduce((s,b)=>s+b.amount,0);$('sumDebt').textContent=money(debt);$('sumPeopleOwe').textContent=money(owe);$('sumOwedMe').textContent=money(owed);$('sumBills').textContent=money(bills)}
function renderAccounts(){const el=$('accountList');if(!state.accounts.length){el.innerHTML=empty('No credit or loan accounts yet.');return}el.innerHTML=state.accounts.map(a=>{const util=a.limit?a.balance/a.limit*100:0;return `<article class="item ${util>=75?'danger':util>=30?'warn':''}"><div class="item-top"><div><strong>${esc(a.name)}</strong><div class="muted">${esc(a.type)} · ${a.apr||0}% APR · Due ${fmtDate(a.due)}</div></div><div class="amount">${money(a.balance)}<div class="muted">Min ${money(a.min)}</div></div></div>${a.limit?`<div class="progress"><span style="width:${Math.min(100,util)}%"></span></div><div class="muted" style="margin-top:6px">${util.toFixed(1)}% utilized of ${money(a.limit)}</div>`:''}<div class="actions"><button class="ghost" data-del-account="${a.id}">Delete</button></div></article>`}).join('')}
function renderPeople(){const el=$('personList');if(!state.people.length){el.innerHTML=empty('No personal debts yet.');return}el.innerHTML=state.people.map(p=>`<article class="item"><div class="item-top"><div><strong>${esc(p.name)}</strong><div class="muted">${p.dir==='i_owe'?'I owe this person':'This person owes me'} · Target ${fmtDate(p.due)}</div></div><div class="amount">${money(p.balance)}<div class="muted">Pay ${money(p.pay)}</div></div></div>${p.notes?`<span class="tag">${esc(p.notes)}</span>`:''}<div class="actions"><button class="ghost" data-del-person="${p.id}">Delete</button></div></article>`).join('')}
function renderBills(){const el=$('billList');if(!state.bills.length){el.innerHTML=empty('No bills yet.');return}el.innerHTML=state.bills.map(b=>{const d=daysUntil(b.due);return `<article class="item ${!b.paid&&d<0?'danger':!b.paid&&d<=5?'warn':b.paid?'good':''}"><div class="item-top"><div><strong>${esc(b.name)}</strong><div class="muted">${esc(b.category)} · ${esc(b.freq)} · ${b.auto?'Autopay':'Manual'}</div></div><div class="amount">${money(b.amount)}<div class="muted">${b.paid?'Paid':'Due '+fmtDate(b.due)}</div></div></div><div class="actions"><button class="ghost" data-toggle-bill="${b.id}">${b.paid?'Mark unpaid':'Mark paid'}</button><button class="ghost" data-del-bill="${b.id}">Delete</button></div></article>`}).join('')}
function renderDashboard(){let alerts=[];state.accounts.forEach(a=>{const u=a.limit?a.balance/a.limit*100:0,d=daysUntil(a.due);if(u>=75)alerts.push({t:`${a.name} utilization is ${u.toFixed(1)}%.`,c:'warn'});if(d<0)alerts.push({t:`${a.name} payment is overdue.`,c:'danger'});else if(d<=5)alerts.push({t:`${a.name} payment is due ${d===0?'today':`in ${d} days`}.`,c:'warn'})});state.bills.filter(b=>!b.paid).forEach(b=>{const d=daysUntil(b.due);if(d<0)alerts.push({t:`${b.name} bill is overdue.`,c:'danger'});else if(d<=5)alerts.push({t:`${b.name} bill is due ${d===0?'today':`in ${d} days`}.`,c:'warn'})});$('alerts').innerHTML=alerts.length?alerts.map(a=>`<div class="item ${a.c}">${esc(a.t)}</div>`).join(''):empty('No alerts right now.');const upcoming=[...state.accounts.map(a=>({name:a.name,amount:a.min,due:a.due,type:'Debt'})),...state.people.filter(p=>p.dir==='i_owe').map(p=>({name:p.name,amount:p.pay,due:p.due,type:'Personal'})),...state.bills.filter(b=>!b.paid).map(b=>({name:b.name,amount:b.amount,due:b.due,type:'Bill'}))].filter(x=>x.due&&daysUntil(x.due)>=0).sort((a,b)=>dateObj(a.due)-dateObj(b.due)).slice(0,6);$('upcomingList').innerHTML=upcoming.length?upcoming.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">${x.type} · ${fmtDate(x.due)}</div></div><strong>${money(x.amount)}</strong></div>`).join(''):empty('Nothing upcoming.')}
function renderPayoff(){const strategy=$('strategy').value;const arr=[...state.accounts].filter(a=>a.balance>0).sort(strategy==='avalanche'?(a,b)=>b.apr-a.apr:(a,b)=>a.balance-b.balance);$('payoffList').innerHTML=arr.length?arr.map((a,i)=>`<article class="item"><div class="item-top"><div><strong>${i+1}. ${esc(a.name)}</strong><div class="muted">${money(a.balance)} · ${a.apr}% APR</div></div><div class="amount">${strategy==='avalanche'?'APR':'Balance'}</div></div></article>`).join(''):empty('Add debt accounts to build a payoff order.')}
function renderPayments(){const el=$('paymentList');el.innerHTML=state.payments.length?state.payments.map(p=>`<article class="item"><div class="item-top"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.type)} · ${fmtDate(p.date)}${p.note?' · '+esc(p.note):''}</div></div><div class="amount">${money(p.amount)}</div></div></article>`).join(''):empty('No payments recorded.')}
function refreshPaymentItems(){const type=$('payType').value;let arr=type==='account'?state.accounts:type==='person'?state.people:state.bills.filter(b=>!b.paid);$('payItem').innerHTML=arr.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')||'<option value="">No items</option>'}

document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(b.dataset.view).classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}));
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.open).showModal()));
$('strategy').addEventListener('change',renderPayoff);$('extraPayment').addEventListener('input',renderPayoff);$('payType').addEventListener('change',refreshPaymentItems);
$('accountFormEl').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return; e.preventDefault();state.accounts.push({id:'a'+Date.now(),name:$('aName').value.trim(),type:$('aType').value,balance:num($('aBalance').value),limit:num($('aLimit').value),apr:num($('aApr').value),min:num($('aMin').value),due:$('aDue').value});e.target.reset();$('accountForm').close();render()});
$('personFormEl').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();state.people.push({id:'p'+Date.now(),name:$('pName').value.trim(),dir:$('pDir').value,balance:num($('pBalance').value),pay:num($('pPay').value),due:$('pDue').value,notes:$('pNotes').value.trim()});e.target.reset();$('personForm').close();render()});
$('billFormEl').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();state.bills.push({id:'b'+Date.now(),name:$('bName').value.trim(),category:$('bCategory').value,amount:num($('bAmount').value),due:$('bDue').value,freq:$('bFreq').value,auto:$('bAuto').checked,paid:false});e.target.reset();$('billForm').close();render()});
$('paymentFormEl').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const type=$('payType').value,id=$('payItem').value,amount=num($('payAmount').value);let obj=type==='account'?state.accounts.find(x=>x.id===id):type==='person'?state.people.find(x=>x.id===id):state.bills.find(x=>x.id===id);if(!obj||amount<=0)return; if(type==='account'||type==='person')obj.balance=Math.max(0,obj.balance-amount); else obj.paid=true;state.payments.unshift({id:'h'+Date.now(),name:obj.name,type:type==='account'?'Credit / Loan':type==='person'?'Personal Debt':'Bill',amount,date:$('payDate').value,note:$('payNote').value.trim()});e.target.reset();$('payDate').value=today();$('paymentForm').close();render()});
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.delAccount){state.accounts=state.accounts.filter(x=>x.id!==t.dataset.delAccount);render()}if(t.dataset.delPerson){state.people=state.people.filter(x=>x.id!==t.dataset.delPerson);render()}if(t.dataset.delBill){state.bills=state.bills.filter(x=>x.id!==t.dataset.delBill);render()}if(t.dataset.toggleBill){const b=state.bills.find(x=>x.id===t.dataset.toggleBill);if(b){b.paid=!b.paid;render()}}});
$('makePlan').addEventListener('click',()=>{const start=dateObj($('nextPayday').value),freq=Number($('payFreq').value),budget=num($('payBudget').value);if(!start){$('paycheckList').innerHTML=empty('Enter your next payday.');return}let html='';for(let i=0;i<6;i++){const d=new Date(start);d.setDate(d.getDate()+i*freq);const end=new Date(d);end.setDate(end.getDate()+freq);const due=[...state.accounts.map(a=>({name:a.name,amount:a.min,due:a.due,type:'Debt'})),...state.people.filter(p=>p.dir==='i_owe').map(p=>({name:p.name,amount:p.pay,due:p.due,type:'Personal'})),...state.bills.filter(b=>!b.paid).map(b=>({name:b.name,amount:b.amount,due:b.due,type:'Bill'}))].filter(x=>{const q=dateObj(x.due);return q&&q>=d&&q<end});const required=due.reduce((s,x)=>s+x.amount,0);html+=`<article class="item"><div class="item-top"><div><strong>Paycheque ${i+1}</strong><div class="muted">${new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',year:'numeric'}).format(d)}</div></div><div class="amount">${money(budget)}</div></div>${due.map(x=>`<div class="row" style="margin-top:10px"><span>${esc(x.name)} <span class="muted">${x.type}</span></span><strong>${money(x.amount)}</strong></div>`).join('')||'<div class="muted" style="margin-top:10px">No tracked payments due.</div>'}<div class="row" style="margin-top:12px;padding-top:10px;border-top:1px solid var(--border)"><span>Remaining</span><strong>${money(Math.max(0,budget-required))}</strong></div></article>`}$('paycheckList').innerHTML=html});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
